// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mego_food/core/storage/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(FavoriteItemModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(FavoriteItemModelAdapter());
  }
}
